INSERT INTO table_livres VALUES(1,'','L''enquete','XIII',13);
INSERT INTO table_livres VALUES(2,'','Le jugement','XIII',12);
INSERT INTO table_livres VALUES(3,'','Lachez les chiens !','XIII',15);
INSERT INTO table_livres VALUES(4,'','Secret defense','XIII',14);
INSERT INTO table_livres VALUES(5,'','Operation Montecristo','XIII',16);
INSERT INTO table_livres VALUES(6,'','Le Jour du soleil noir','XIII',1);
INSERT INTO table_livres VALUES(7,'','La Version irlandaise','XIII',18);
INSERT INTO table_livres VALUES(8,'','Toutes les larmes de l''enfer','XIII',3);
INSERT INTO table_livres VALUES(9,'','L''Or de Maximilien','XIII',17);
INSERT INTO table_livres VALUES(10,'','La ou va l''indien','XIII',2);
INSERT INTO table_livres VALUES(11,'','Le dernier round','XIII',19);
INSERT INTO table_livres VALUES(12,'','Spads','XIII',4);
INSERT INTO table_livres VALUES(13,'','Dossier Jason Fly','XIII',6);
INSERT INTO table_livres VALUES(14,'','Rouge total','XIII',5);
INSERT INTO table_livres VALUES(15,'','XIII contre un','XIII',8);
INSERT INTO table_livres VALUES(16,'','La Nuit du 3 aout','XIII',7);
INSERT INTO table_livres VALUES(17,'','El Cascador','XIII',10);
INSERT INTO table_livres VALUES(18,'','Pour Maria','XIII',9);
INSERT INTO table_livres VALUES(19,'','Trois Montres d''argent','XIII',11);
INSERT INTO table_livres VALUES(20,'','Lucien se met au vert','Lucien',4);
INSERT INTO table_livres VALUES(21,'','Lucien, le retour','Lucien',5);
INSERT INTO table_livres VALUES(22,'','Bananes metalliques','Lucien',6);
INSERT INTO table_livres VALUES(23,'','Week-end motard','Lucien',8);
INSERT INTO table_livres VALUES(24,'','Radio Lucien','Lucien',1);
INSERT INTO table_livres VALUES(25,'','Chez Lucien','Lucien',2);
INSERT INTO table_livres VALUES(26,'','Lulu s''maque','Lucien',3);
INSERT INTO table_livres VALUES(27,'2-8036-0021-8','Le retour de Chlorophylle','Chlorophylle',6);
INSERT INTO table_livres VALUES(28,'2-8036-0389-6','Chloro a la rescousse','Chlorophylle',7);
INSERT INTO table_livres VALUES(29,'2-8036-0490-6','Faits divers','Chlorophylle',8);
INSERT INTO table_livres VALUES(30,'2-8036-0539-2','Les yeux noirs','Chlorophylle',9);
INSERT INTO table_livres VALUES(31,'2-8036-0546-5','Les bouseux','Chlorophylle',10);
INSERT INTO table_livres VALUES(32,'2-8036-0570-8','Barrages','Chlorophylle',11);
INSERT INTO table_livres VALUES(33,'2-8036-0604-6','Les trois mercenaires','Chlorophylle',12);
INSERT INTO table_livres VALUES(34,'2-8036-0665-8','Le testament d''Anthracite','Chlorophylle',13);
INSERT INTO table_livres VALUES(36,'','La mysterieuse escadrille delta','Tanguy et Laverdure (L''integrale)',0);
INSERT INTO table_livres VALUES(37,'','L''espion venu du ciel','Tanguy et Laverdure (L''integrale)',0);
INSERT INTO table_livres VALUES(38,'','L''ecole des aigles','Tanguy et Laverdure (L''integrale)',0);
INSERT INTO table_livres VALUES(39,'','L''escadrille des cigognes','Tanguy et Laverdure (L''integrale)',0);
INSERT INTO table_livres VALUES(40,'','Cap zero','Tanguy et Laverdure (L''integrale)',0);
INSERT INTO table_livres VALUES(41,'','Menace sur Mururoa','Tanguy et Laverdure (L''integrale)',0);
INSERT INTO table_livres VALUES(42,'','Lieutenant double-bang','Tanguy et Laverdure (L''integrale)',0);
INSERT INTO table_livres VALUES(43,'','La terreur vient du ciel','Tanguy et Laverdure (L''integrale)',0);
INSERT INTO table_livres VALUES(44,'','Le petit bleu de la cote ouest','Tardi',0);
INSERT INTO table_livres VALUES(45,'','Le Cri du peuple Integrale','Tardi',0);
INSERT INTO table_livres VALUES(46,'','Integrale Le cri du peuple, Tomes 1 a 4','Tardi',0);
INSERT INTO table_livres VALUES(47,'','Sibylline (1969 - 1974)Integrale','Integrale Sibylline',2);
INSERT INTO table_livres VALUES(48,'','Sibylline (1965 - 1969)Integrale','Integrale Sibylline',1);
INSERT INTO table_livres VALUES(49,'','La Cyclope','Largo Winch',2);
INSERT INTO table_livres VALUES(50,'','Business Blues','Largo Winch',6);
INSERT INTO table_livres VALUES(51,'','Clifton - Integrale','Clifton - Integrale',1);
INSERT INTO table_livres VALUES(52,'','Clifton - Integrale','Clifton - Integrale',2);
INSERT INTO table_livres VALUES(53,'','Clifton - Integrale','Clifton - Integrale',3);
INSERT INTO table_livres VALUES(54,'','Clifton - Integrale','Clifton - Integrale',4);
INSERT INTO table_livres VALUES(55,'','Clifton - Integrale','Clifton - Integrale',5);
INSERT INTO table_livres VALUES(56,'','Le Cycle des Krygonites C.1','Les aventuriers du NHL2987 Survivaure',1);
INSERT INTO table_livres VALUES(57,'','Premiere saison (Partie 1)','Le donjon de Naheulbeuk',1);
INSERT INTO table_livres VALUES(58,'','Premiere saison (Partie 2)','Le donjon de Naheulbeuk',2);
INSERT INTO table_livres VALUES(59,'','Deuxieme saison (Partie 1)','Le donjon de Naheulbeuk',3);
INSERT INTO table_livres VALUES(60,'','Deuxieme saison (Partie 2)','Le donjon de Naheulbeuk',4);
INSERT INTO table_livres VALUES(61,'','Deuxieme saison (Partie 3)','Le donjon de Naheulbeuk',5);
INSERT INTO table_livres VALUES(62,'','Deuxieme saison (Partie 4)','Le donjon de Naheulbeuk',6);
INSERT INTO table_livres VALUES(63,'','60 gags de Boule et Bill','Boule et Bill',1);
INSERT INTO table_livres VALUES(64,'','Mars le noir','Marsupilami',3);
INSERT INTO table_livres VALUES(65,'','Le Pollen du Monte Urticando','Marsupilami',4);
INSERT INTO table_livres VALUES(66,'','La Queue du Marsupilami','Marsupilami',1);
INSERT INTO table_livres VALUES(67,'','Le Bebe du bout du monde','Marsupilami',2);
INSERT INTO table_livres VALUES(68,'','Integrale cycle 1- T1 a T5','Merlin - Integrale',1);
INSERT INTO table_livres VALUES(69,'','Coffret Tomes 1 a 5','Soeur Marie-Therese des Batignolles',0);
INSERT INTO table_livres VALUES(70,'','Les bleus en folie','Les Tuniques Bleues',32);
INSERT INTO table_livres VALUES(71,'','Un chariot dans l''Ouest','Les Tuniques Bleues',1);
INSERT INTO table_livres VALUES(72,'','Qui veut la peau du General ?','Les Tuniques Bleues',42);
INSERT INTO table_livres VALUES(73,'','El Padre','Les Tuniques Bleues',17);
INSERT INTO table_livres VALUES(74,'','Grumbler et fils','Les Tuniques Bleues',33);
INSERT INTO table_livres VALUES(75,'','Du Nord au Sud','Les Tuniques Bleues',2);
INSERT INTO table_livres VALUES(76,'','Les Nancy Hart','Les Tuniques Bleues',47);
INSERT INTO table_livres VALUES(77,'','Blue retro','Les Tuniques Bleues',18);
INSERT INTO table_livres VALUES(78,'','Vertes annees','Les Tuniques Bleues',34);
INSERT INTO table_livres VALUES(79,'','Et pour quinze cents dollars en plus','Les Tuniques Bleues',3);
INSERT INTO table_livres VALUES(80,'','Arabesque','Les Tuniques Bleues',48);
INSERT INTO table_livres VALUES(81,'','Le David','Les Tuniques Bleues',19);
INSERT INTO table_livres VALUES(82,'','Captain Nepel','Les Tuniques Bleues',35);
INSERT INTO table_livres VALUES(83,'','Outlaw','Les Tuniques Bleues',4);
INSERT INTO table_livres VALUES(84,'','Mariage a Fort Bow','Les Tuniques Bleues',49);
INSERT INTO table_livres VALUES(85,'','Black Face','Les Tuniques Bleues',20);
INSERT INTO table_livres VALUES(86,'','Quantrill','Les Tuniques Bleues',36);
INSERT INTO table_livres VALUES(87,'','Les Deserteurs','Les Tuniques Bleues',5);
INSERT INTO table_livres VALUES(88,'','La traque','Les Tuniques Bleues',50);
INSERT INTO table_livres VALUES(89,'','Les cinq salopards','Les Tuniques Bleues',21);
INSERT INTO table_livres VALUES(90,'','Duel dans la Manche','Les Tuniques Bleues',37);
INSERT INTO table_livres VALUES(91,'','La prison de Robertsonville','Les Tuniques Bleues',6);
INSERT INTO table_livres VALUES(92,'','Stark sous toutes les coutures','Les Tuniques Bleues',51);
INSERT INTO table_livres VALUES(93,'','Des bleus et des dentelles','Les Tuniques Bleues',22);
INSERT INTO table_livres VALUES(94,'','Les planques','Les Tuniques Bleues',38);
INSERT INTO table_livres VALUES(95,'','Les Bleus de la marine','Les Tuniques Bleues',7);
INSERT INTO table_livres VALUES(96,'','Miss Walker','Les Tuniques Bleues',54);
INSERT INTO table_livres VALUES(97,'','Les cousins d''en face','Les Tuniques Bleues',23);
INSERT INTO table_livres VALUES(98,'','Puppet Blues','Les Tuniques Bleues',39);
INSERT INTO table_livres VALUES(99,'','Les Cavaliers du ciel','Les Tuniques Bleues',8);
INSERT INTO table_livres VALUES(100,'','Indien, Mon Frere','Les Tuniques Bleues',55);
INSERT INTO table_livres VALUES(101,'','Les hommes de paille','Les Tuniques Bleues',40);
INSERT INTO table_livres VALUES(102,'','La Grande patrouille','Les Tuniques Bleues',9);
INSERT INTO table_livres VALUES(104,'','Baby blue','Les Tuniques Bleues',24);
INSERT INTO table_livres VALUES(105,'','Les bleus en cavale','Les Tuniques Bleues',41);
INSERT INTO table_livres VALUES(106,'','Des bleus et des tuniques','Les Tuniques Bleues',10);
INSERT INTO table_livres VALUES(108,'','Des bleus et des bosses','Les Tuniques Bleues',25);
INSERT INTO table_livres VALUES(109,'','Des bleus dans le brouillard','Les Tuniques Bleues',52);
INSERT INTO table_livres VALUES(110,'','Des bleus en noir et blanc','Les Tuniques Bleues',11);
INSERT INTO table_livres VALUES(112,'','L''or du Quebec','Les Tuniques Bleues',26);
INSERT INTO table_livres VALUES(113,'','Sang bleu chez les bleus','Les Tuniques Bleues',53);
INSERT INTO table_livres VALUES(114,'','Les bleus tournent cosaques','Les Tuniques Bleues',12);
INSERT INTO table_livres VALUES(116,'','Bull Run','Les Tuniques Bleues',27);
INSERT INTO table_livres VALUES(117,'','L''oreille de Lincoln','Les Tuniques Bleues',44);
INSERT INTO table_livres VALUES(118,'','Les bleus dans la gadoue','Les Tuniques Bleues',13);
INSERT INTO table_livres VALUES(119,'','Les bleus de la balle','Les Tuniques Bleues',28);
INSERT INTO table_livres VALUES(120,'','Requiem pour un Bleu','Les Tuniques Bleues',46);
INSERT INTO table_livres VALUES(121,'','Le blanc-bec','Les Tuniques Bleues',14);
INSERT INTO table_livres VALUES(122,'','En avant l''amnesique !','Les Tuniques Bleues',29);
INSERT INTO table_livres VALUES(123,'','Des bleus et du blues','Les Tuniques Bleues',43);
INSERT INTO table_livres VALUES(124,'','Rumberley','Les Tuniques Bleues',15);
INSERT INTO table_livres VALUES(125,'','La rose de Bantry','Les Tuniques Bleues',30);
INSERT INTO table_livres VALUES(126,'','emeutes a New-York','Les Tuniques Bleues',45);
INSERT INTO table_livres VALUES(127,'','Bronco Benny','Les Tuniques Bleues',16);
INSERT INTO table_livres VALUES(128,'','Drummer Boy','Les Tuniques Bleues',31);
INSERT INTO table_livres VALUES(130,'','Asterix et Latraviata','Asterix',31);
INSERT INTO table_livres VALUES(131,'','Asterix chez les Helvetes','Asterix',16);
INSERT INTO table_livres VALUES(133,'','La Serpe d''or','Asterix',2);
INSERT INTO table_livres VALUES(134,'','Le domaine des Dieux','Asterix',17);
INSERT INTO table_livres VALUES(136,'','Asterix et les Goths','Asterix',3);
INSERT INTO table_livres VALUES(138,'','Le Combat des chefs','Asterix',7);
INSERT INTO table_livres VALUES(140,'','Le Devin','Asterix',19);
INSERT INTO table_livres VALUES(143,'','Asterix En Corse','Asterix',20);
INSERT INTO table_livres VALUES(145,'','La Zizanie','Asterix',15);
INSERT INTO table_livres VALUES(146,'','Le Tour de Gaule d''Asterix','Asterix',5);
INSERT INTO table_livres VALUES(147,'','Le Cadeau de Cesar','Asterix',21);
INSERT INTO table_livres VALUES(149,'','Asterix et Cleopatre','Asterix',6);
INSERT INTO table_livres VALUES(150,'','La grande traversee','Asterix',22);
INSERT INTO table_livres VALUES(155,'','Asterix chez les Bretons','Asterix',8);
INSERT INTO table_livres VALUES(156,'','Asterix chez les Belges','Asterix',24);
INSERT INTO table_livres VALUES(158,'','Asterix et les Normands','Asterix',9);
INSERT INTO table_livres VALUES(159,'','Le grand fosse','Asterix',25);
INSERT INTO table_livres VALUES(160,'','Asterix legionnaire','Asterix',10);
INSERT INTO table_livres VALUES(162,'','L''odyssee d''Asterix','Asterix',26);
INSERT INTO table_livres VALUES(163,'','Les Lauriers de Cesar','Asterix',18);
INSERT INTO table_livres VALUES(164,'','Le bouclier arverne','Asterix',11);
INSERT INTO table_livres VALUES(165,'','Le Fils d''Asterix','Asterix',27);
INSERT INTO table_livres VALUES(166,'','Obelix et compagnie','Asterix',23);
INSERT INTO table_livres VALUES(167,'','Asterix aux Jeux Olympiques','Asterix',12);
INSERT INTO table_livres VALUES(168,'','Asterix chez Rahazade','Asterix',28);
INSERT INTO table_livres VALUES(169,'','Asterix le Gaulois','Asterix',1);
INSERT INTO table_livres VALUES(170,'','Asterix et le chaudron','Asterix',13);
INSERT INTO table_livres VALUES(171,'','La Rose et le Glaive','Asterix',29);
INSERT INTO table_livres VALUES(172,'','Asterix gladiateur','Asterix',4);
INSERT INTO table_livres VALUES(173,'','Asterix en Hispanie','Asterix',14);
INSERT INTO table_livres VALUES(174,'','La galere d''Obelix','Asterix',30);
INSERT INTO table_livres VALUES(175,'','Alinoe','Thorgal',8);
INSERT INTO table_livres VALUES(176,'','Les Archers','Thorgal',9);
INSERT INTO table_livres VALUES(177,'','Le Pays Qa','Thorgal',10);
INSERT INTO table_livres VALUES(178,'','Les yeux de Tanatloc','Thorgal',11);
INSERT INTO table_livres VALUES(179,'','Arachnea','Thorgal',24);
INSERT INTO table_livres VALUES(180,'','La cite du Dieu perdu','Thorgal',12);
INSERT INTO table_livres VALUES(181,'','La cage','Thorgal',23);
INSERT INTO table_livres VALUES(182,'','Entre terre et lumiere','Thorgal',13);
INSERT INTO table_livres VALUES(183,'','Geants','Thorgal',22);
INSERT INTO table_livres VALUES(184,'','Le maitre des montagnes','Thorgal',15);
INSERT INTO table_livres VALUES(185,'','Aaricia','Thorgal',14);
INSERT INTO table_livres VALUES(186,'','Les trois vieillards du pays d''Aran','Thorgal',3);
INSERT INTO table_livres VALUES(187,'','La galere noire','Thorgal',4);
INSERT INTO table_livres VALUES(188,'','La magicienne trahie','Thorgal',1);
INSERT INTO table_livres VALUES(189,'','L''ile des mers gelees','Thorgal',2);
INSERT INTO table_livres VALUES(190,'','Au-dela des ombres','Thorgal',5);
INSERT INTO table_livres VALUES(191,'','La chute de Brek-Zarith','Thorgal',6);
INSERT INTO table_livres VALUES(192,'','L''enfant des etoiles','Thorgal',7);
INSERT INTO table_livres VALUES(193,'','Tome 2','Ric Hochet - Integrales',2);
INSERT INTO table_livres VALUES(194,'','Tome 1','Ric Hochet - Integrales',1);
INSERT INTO table_livres VALUES(195,'','Tome 16','Ric Hochet - Integrales',16);
INSERT INTO table_livres VALUES(196,'','Tome 14','Ric Hochet - Integrales',14);
INSERT INTO table_livres VALUES(197,'','Tome 13','Ric Hochet - Integrales',13);
INSERT INTO table_livres VALUES(198,'','Tome 12','Ric Hochet - Integrales',12);
INSERT INTO table_livres VALUES(199,'','Tome 11','Ric Hochet - Integrales',11);
INSERT INTO table_livres VALUES(200,'','Tome 10','Ric Hochet - Integrales',10);
INSERT INTO table_livres VALUES(201,'','Tome 9','Ric Hochet - Integrales',9);
INSERT INTO table_livres VALUES(202,'','Tome 8','Ric Hochet - Integrales',8);
INSERT INTO table_livres VALUES(203,'','Tome 7','Ric Hochet - Integrales',7);
INSERT INTO table_livres VALUES(204,'','Tome 6','Ric Hochet - Integrales',6);
INSERT INTO table_livres VALUES(205,'','Tome 5','Ric Hochet - Integrales',5);
INSERT INTO table_livres VALUES(206,'','Tome 4','Ric Hochet - Integrales',4);
INSERT INTO table_livres VALUES(207,'','Tome 3','Ric Hochet - Integrales',3);
INSERT INTO table_livres VALUES(208,'','Litteul Kevin','Litteul Kevin',8);
INSERT INTO table_livres VALUES(209,'','Litteul Kevin','Litteul Kevin',1);
INSERT INTO table_livres VALUES(210,'','Litteul Kevin','Litteul Kevin',3);
INSERT INTO table_livres VALUES(211,'','Litteul Kevin','Litteul Kevin',5);
INSERT INTO table_livres VALUES(212,'','Litteul Kevin','Litteul Kevin',6);
INSERT INTO table_livres VALUES(213,'','Litteul Kevin','Litteul Kevin',4);
INSERT INTO table_livres VALUES(214,'','Litteul Kevin','Litteul Kevin',2);
INSERT INTO table_livres VALUES(215,'','Litteul Kevin','Litteul Kevin',7);
INSERT INTO table_livres VALUES(216,'','Integrale 2','Integrale Bernard Prince',2);
INSERT INTO table_livres VALUES(217,'','Integrale 1','Integrale Bernard Prince',1);
INSERT INTO table_livres VALUES(218,'','La guerre noire','I.R.$.',8);
INSERT INTO table_livres VALUES(219,'','Corporate America','I.R.$.',7);
INSERT INTO table_livres VALUES(220,'','Le Corrupteur','I.R.$.',6);
INSERT INTO table_livres VALUES(221,'','Silicia Inc.','I.R.$.',5);
INSERT INTO table_livres VALUES(222,'','Narcocratie','I.R.$.',4);
INSERT INTO table_livres VALUES(223,'','Blue Ice','I.R.$.',3);
INSERT INTO table_livres VALUES(224,'','La strategie Hagen','I.R.$.',2);
INSERT INTO table_livres VALUES(225,'','La voie fiscale','I.R.$.',1);
INSERT INTO table_livres VALUES(226,'','Au Nom du President','I.R.$.',12);
INSERT INTO table_livres VALUES(227,'','Le Chemin de Gloria','I.R.$.',11);
INSERT INTO table_livres VALUES(228,'','La loge des assassins','I.R.$.',10);
INSERT INTO table_livres VALUES(229,'','Liaisons romaines','I.R.$.',9);
INSERT INTO table_livres VALUES(230,'','L''ennemi','Buddy Longway',2);
INSERT INTO table_livres VALUES(231,'','Hooka-Hey','Buddy Longway',15);
INSERT INTO table_livres VALUES(232,'','Premieres chasses','Buddy Longway',9);
INSERT INTO table_livres VALUES(233,'','L''eau de feu','Buddy Longway',8);
INSERT INTO table_livres VALUES(234,'','L''orignal','Buddy Longway',6);
INSERT INTO table_livres VALUES(235,'','Le secret','Buddy Longway',5);
INSERT INTO table_livres VALUES(236,'','Seul','Buddy Longway',4);
INSERT INTO table_livres VALUES(237,'','Trois hommes sont passes','Buddy Longway',3);
INSERT INTO table_livres VALUES(238,'','Chinook','Buddy Longway',1);
INSERT INTO table_livres VALUES(239,'','L''hiver des chevaux','Buddy Longway',7);
INSERT INTO table_livres VALUES(240,'','Capitaine Ryan','Buddy Longway',12);
INSERT INTO table_livres VALUES(241,'','Le vent sauvage','Buddy Longway',13);
INSERT INTO table_livres VALUES(242,'','Le vol du Wallenstein','Biggles',7);
INSERT INTO table_livres VALUES(243,'','Le bal des Spitfire','Biggles',3);
INSERT INTO table_livres VALUES(244,'','La bataille d''Angleterre','Biggles',1);
INSERT INTO table_livres VALUES(245,'','La bataille de France','Biggles',2);
INSERT INTO table_livres VALUES(246,'','Squadron Biggles','Biggles',4);
INSERT INTO table_livres VALUES(247,'','Le cygne jaune','Biggles',5);
INSERT INTO table_livres VALUES(248,'','Les pirates du Pole Sud','Biggles',6);
INSERT INTO table_livres VALUES(249,'','La 13eme dent du diable','Biggles',8);
INSERT INTO table_livres VALUES(250,'','Le dernier Zeppelin','Biggles',9);
INSERT INTO table_livres VALUES(251,'','Tonton Placide','Benoit Brisefer',4);
INSERT INTO table_livres VALUES(252,'','Les douze travaux de Benoit Brisefer','Benoit Brisefer',3);
INSERT INTO table_livres VALUES(253,'','Madame Adolphine','Benoit Brisefer',2);
INSERT INTO table_livres VALUES(254,'','Les taxis rouges','Benoit Brisefer',1);
INSERT INTO table_livres VALUES(255,'','Les Passagers du vent','Les Passagers du vent',1);
INSERT INTO table_livres VALUES(256,'','Les Passagers du vent','Les Passagers du vent',2);
INSERT INTO table_livres VALUES(257,'','Les Passagers du vent','Les Passagers du vent',3);
INSERT INTO table_livres VALUES(258,'','Les Passagers du vent','Les Passagers du vent',4);
INSERT INTO table_livres VALUES(259,'','Les Passagers du vent','Les Passagers du vent',5);
INSERT INTO table_livres VALUES(260,'','Les Passagers du vent','Les Passagers du vent',6);
INSERT INTO table_livres VALUES(261,'','Le feu de Wotan','Yoko Tsuno',14);
INSERT INTO table_livres VALUES(262,'','Le matin du monde','Yoko Tsuno',17);
INSERT INTO table_livres VALUES(263,'','Les exiles de Kifa','Yoko Tsuno',18);
INSERT INTO table_livres VALUES(264,'','La porte des ames','Yoko Tsuno',21);
INSERT INTO table_livres VALUES(265,'','La jonque celeste','Yoko Tsuno',22);
INSERT INTO table_livres VALUES(266,'','Le trio de l''etrange','Yoko Tsuno',1);
INSERT INTO table_livres VALUES(267,'','La proie et l''ombre','Yoko Tsuno',12);
INSERT INTO table_livres VALUES(268,'','L''orgue du diable','Yoko Tsuno',2);
INSERT INTO table_livres VALUES(269,'','La forge de vulcain','Yoko Tsuno',3);
INSERT INTO table_livres VALUES(270,'','Aventures electroniques','Yoko Tsuno',4);
INSERT INTO table_livres VALUES(271,'','Message pour l''eternite','Yoko Tsuno',5);
INSERT INTO table_livres VALUES(272,'','Les 3 soleils de Vinea','Yoko Tsuno',6);
INSERT INTO table_livres VALUES(273,'','La frontiere de la vie','Yoko Tsuno',7);
INSERT INTO table_livres VALUES(274,'','Les titans','Yoko Tsuno',8);
INSERT INTO table_livres VALUES(275,'','La fille du vent','Yoko Tsuno',9);
INSERT INTO table_livres VALUES(276,'','La lumiere d''Ixo','Yoko Tsuno',10);
INSERT INTO table_livres VALUES(277,'','La spirale du temps','Yoko Tsuno',11);
INSERT INTO table_livres VALUES(278,'','La proie et l''ombre','Yoko Tsuno',12);
INSERT INTO table_livres VALUES(279,'','Premieres enquetes','Canardo',0);
INSERT INTO table_livres VALUES(280,'','La fille qui revait d''horizon','Canardo',10);
INSERT INTO table_livres VALUES(281,'','Le Voyage des cendres','Canardo',19);
INSERT INTO table_livres VALUES(282,'','Une bavure bien baveuse','Canardo',20);
INSERT INTO table_livres VALUES(283,'','La nurse aux mains sanglantes','Canardo',12);
INSERT INTO table_livres VALUES(284,'','Un miserable petit tas de secrets','Canardo',11);
INSERT INTO table_livres VALUES(285,'','Le Buveur en col blanc','Canardo',13);
INSERT INTO table_livres VALUES(286,'','Maree noire','Canardo',14);
INSERT INTO table_livres VALUES(287,'','L''affaire belge','Canardo',15);
INSERT INTO table_livres VALUES(288,'','La fille sans visage','Canardo',18);
INSERT INTO table_livres VALUES(289,'','Une bourgeoise fatale','Canardo',17);
INSERT INTO table_livres VALUES(290,'','L''ombre de la bete','Canardo',16);
INSERT INTO table_livres VALUES(291,'','Putain de Guerre','Tardi',0);
INSERT INTO table_livres VALUES(292,'','Le Der des Ders','Tardi',0);
INSERT INTO table_livres VALUES(293,'','Griffu','Tardi',0);
INSERT INTO table_livres VALUES(294,'','C''etait la guerre des tranchees','Tardi',0);
INSERT INTO table_livres VALUES(295,'','M''as-tu vu en cadavre ?','Nestor Burma',0);
INSERT INTO table_livres VALUES(296,'','120, rue de la Gare','Nestor Burma',0);
INSERT INTO table_livres VALUES(297,'','Brouillard au pont de Tolbiac','Nestor Burma',1);
INSERT INTO table_livres VALUES(298,'','Casse-pipe a la nation','Nestor Burma',0);
INSERT INTO table_livres VALUES(299,'','One piece','One piece',21);
INSERT INTO table_livres VALUES(300,'','One piece','One piece',37);
INSERT INTO table_livres VALUES(301,'','One piece','One piece',5);
INSERT INTO table_livres VALUES(302,'','One piece','One piece',52);
INSERT INTO table_livres VALUES(303,'','One piece','One piece',22);
INSERT INTO table_livres VALUES(304,'','One piece','One piece',38);
INSERT INTO table_livres VALUES(305,'','One piece','One piece',6);
INSERT INTO table_livres VALUES(306,'','One piece','One piece',53);
INSERT INTO table_livres VALUES(307,'','One piece','One piece',23);
INSERT INTO table_livres VALUES(308,'','One piece','One piece',39);
INSERT INTO table_livres VALUES(309,'','One piece','One piece',7);
INSERT INTO table_livres VALUES(310,'','One piece','One piece',54);
INSERT INTO table_livres VALUES(311,'','One piece','One piece',24);
INSERT INTO table_livres VALUES(312,'','One piece','One piece',40);
INSERT INTO table_livres VALUES(313,'','One piece','One piece',8);
INSERT INTO table_livres VALUES(314,'','One piece','One piece',55);
INSERT INTO table_livres VALUES(315,'','One piece','One piece',25);
INSERT INTO table_livres VALUES(316,'','One piece','One piece',41);
INSERT INTO table_livres VALUES(317,'','One piece','One piece',9);
INSERT INTO table_livres VALUES(318,'','One Piece','One piece',56);
INSERT INTO table_livres VALUES(319,'','One piece','One piece',26);
INSERT INTO table_livres VALUES(320,'','One piece','One piece',42);
INSERT INTO table_livres VALUES(321,'','One piece','One piece',10);
INSERT INTO table_livres VALUES(322,'','One piece','One piece',57);
INSERT INTO table_livres VALUES(323,'','One piece','One piece',27);
INSERT INTO table_livres VALUES(324,'','One piece','One piece',43);
INSERT INTO table_livres VALUES(325,'','One piece','One piece',11);
INSERT INTO table_livres VALUES(326,'','One Piece','One piece',58);
INSERT INTO table_livres VALUES(327,'','One piece','One piece',28);
INSERT INTO table_livres VALUES(328,'','One piece','One piece',44);
INSERT INTO table_livres VALUES(329,'','One piece','One piece',12);
INSERT INTO table_livres VALUES(330,'','One piece','One piece',59);
INSERT INTO table_livres VALUES(331,'','One piece','One piece',29);
INSERT INTO table_livres VALUES(332,'','One piece','One piece',45);
INSERT INTO table_livres VALUES(333,'','One piece','One piece',13);
INSERT INTO table_livres VALUES(334,'','One piece','One piece',60);
INSERT INTO table_livres VALUES(335,'','One piece','One piece',30);
INSERT INTO table_livres VALUES(336,'','One piece','One piece',46);
INSERT INTO table_livres VALUES(337,'','One piece','One piece',14);
INSERT INTO table_livres VALUES(338,'','One Piece','One piece',61);
INSERT INTO table_livres VALUES(339,'','One piece','One piece',31);
INSERT INTO table_livres VALUES(340,'','One piece','One piece',47);
INSERT INTO table_livres VALUES(341,'','One piece','One piece',15);
INSERT INTO table_livres VALUES(342,'','One piece','One piece',32);
INSERT INTO table_livres VALUES(343,'','One piece','One piece',48);
INSERT INTO table_livres VALUES(344,'','One piece','One piece',16);
INSERT INTO table_livres VALUES(345,'','One piece','One piece',33);
INSERT INTO table_livres VALUES(346,'','One piece','One piece',1);
INSERT INTO table_livres VALUES(347,'','One piece','One piece',49);
INSERT INTO table_livres VALUES(348,'','One piece','One piece',17);
INSERT INTO table_livres VALUES(349,'','One piece','One piece',34);
INSERT INTO table_livres VALUES(350,'','One piece','One piece',2);
INSERT INTO table_livres VALUES(351,'','One piece','One piece',18);
INSERT INTO table_livres VALUES(352,'','One piece','One piece',35);
INSERT INTO table_livres VALUES(353,'','One piece','One piece',3);
INSERT INTO table_livres VALUES(354,'','One piece','One piece',50);
INSERT INTO table_livres VALUES(355,'','One piece','One piece',19);
INSERT INTO table_livres VALUES(356,'','One piece','One piece',36);
INSERT INTO table_livres VALUES(357,'','One piece','One piece',4);
INSERT INTO table_livres VALUES(358,'','One piece','One piece',51);
INSERT INTO table_livres VALUES(359,'','One piece','One piece',20);
INSERT INTO table_livres VALUES(360,'','Dragon ball','Dragon ball',7);
INSERT INTO table_livres VALUES(361,'','Dragon ball','Dragon ball',23);
INSERT INTO table_livres VALUES(362,'','Dragon ball','Dragon ball',39);
INSERT INTO table_livres VALUES(363,'','Dragon ball','Dragon ball',8);
INSERT INTO table_livres VALUES(364,'','Dragon ball','Dragon ball',24);
INSERT INTO table_livres VALUES(365,'','Dragon ball','Dragon ball',40);
INSERT INTO table_livres VALUES(366,'','Dragon ball','Dragon ball',9);
INSERT INTO table_livres VALUES(367,'','Dragon ball','Dragon ball',25);
INSERT INTO table_livres VALUES(368,'','Dragon ball','Dragon ball',41);
INSERT INTO table_livres VALUES(369,'','Dragon ball','Dragon ball',10);
INSERT INTO table_livres VALUES(370,'','Dragon ball','Dragon ball',26);
INSERT INTO table_livres VALUES(371,'','Dragon ball','Dragon ball',42);
INSERT INTO table_livres VALUES(372,'','Dragon ball','Dragon ball',11);
INSERT INTO table_livres VALUES(373,'','Dragon ball','Dragon ball',27);
INSERT INTO table_livres VALUES(374,'','Dragon ball','Dragon ball',12);
INSERT INTO table_livres VALUES(375,'','Dragon ball','Dragon ball',28);
INSERT INTO table_livres VALUES(376,'','Dragon ball','Dragon ball',13);
INSERT INTO table_livres VALUES(377,'','Dragon ball','Dragon ball',29);
INSERT INTO table_livres VALUES(378,'','Dragon ball','Dragon ball',14);
INSERT INTO table_livres VALUES(379,'','Dragon ball','Dragon ball',30);
INSERT INTO table_livres VALUES(380,'','Dragon ball','Dragon ball',15);
INSERT INTO table_livres VALUES(381,'','Dragon ball','Dragon ball',31);
INSERT INTO table_livres VALUES(382,'','Dragon ball','Dragon ball',16);
INSERT INTO table_livres VALUES(383,'','Dragon ball','Dragon ball',32);
INSERT INTO table_livres VALUES(384,'','Dragon ball','Dragon ball',1);
INSERT INTO table_livres VALUES(385,'','Dragon ball','Dragon ball',17);
INSERT INTO table_livres VALUES(386,'','Dragon ball','Dragon ball',33);
INSERT INTO table_livres VALUES(387,'','Dragon ball','Dragon ball',2);
INSERT INTO table_livres VALUES(388,'','Dragon ball','Dragon ball',18);
INSERT INTO table_livres VALUES(389,'','Dragon ball','Dragon ball',34);
INSERT INTO table_livres VALUES(390,'','Dragon ball','Dragon ball',3);
INSERT INTO table_livres VALUES(391,'','Dragon ball','Dragon ball',19);
INSERT INTO table_livres VALUES(392,'','Dragon ball','Dragon ball',35);
INSERT INTO table_livres VALUES(393,'','Dragon ball','Dragon ball',4);
INSERT INTO table_livres VALUES(394,'','Dragon ball','Dragon ball',20);
INSERT INTO table_livres VALUES(395,'','Dragon ball','Dragon ball',36);
INSERT INTO table_livres VALUES(396,'','Dragon ball','Dragon ball',5);
INSERT INTO table_livres VALUES(397,'','Dragon ball','Dragon ball',21);
INSERT INTO table_livres VALUES(398,'','Dragon ball','Dragon ball',37);
INSERT INTO table_livres VALUES(399,'','Dragon ball','Dragon ball',6);
INSERT INTO table_livres VALUES(400,'','Dragon ball','Dragon ball',22);
INSERT INTO table_livres VALUES(401,'','Dragon ball','Dragon ball',38);
INSERT INTO table_livres VALUES(402,'','Joe Bar Team','Joe Bar Team',2);
INSERT INTO table_livres VALUES(403,'','Joe Bar Team','Joe Bar Team',5);
INSERT INTO table_livres VALUES(404,'','Joe Bar Team','Joe Bar Team',6);
INSERT INTO table_livres VALUES(405,'','Joe Bar Team','Joe Bar Team',7);
INSERT INTO table_livres VALUES(406,'','Joe Bar Team','Joe Bar Team',1);
INSERT INTO table_livres VALUES(407,'','Joe Bar Team','Joe Bar Team',3);
INSERT INTO table_livres VALUES(408,'','Joe Bar Team','Joe Bar Team',4);
INSERT INTO table_livres VALUES(409,'','Coffret Tomes 01 a 04','Gorn',1);
INSERT INTO table_livres VALUES(410,'','La Loi du preau','Titeuf',9);
INSERT INTO table_livres VALUES(411,'','Nadia se marie','Titeuf',10);
INSERT INTO table_livres VALUES(412,'','Mes meilleurs copains','Titeuf',11);
INSERT INTO table_livres VALUES(413,'','Le sens de la vie','Titeuf',12);
INSERT INTO table_livres VALUES(415,'','Dieu, le sexe et les bretelles','Titeuf',1);
INSERT INTO table_livres VALUES(416,'','L''amour, c''est po propre ?','Titeuf',2);
INSERT INTO table_livres VALUES(417,'','Ca epate les filles','Titeuf',3);
INSERT INTO table_livres VALUES(418,'','C''est po juste?','Titeuf',4);
INSERT INTO table_livres VALUES(419,'','Et le Derriere des choses','Titeuf',5);
INSERT INTO table_livres VALUES(420,'','Tcho, monde cruel','Titeuf',6);
INSERT INTO table_livres VALUES(421,'','Le miracle de la vie','Titeuf',7);
INSERT INTO table_livres VALUES(422,'','Lachez-moi le slip !','Titeuf',8);
INSERT INTO table_livres VALUES(423,'','Le Chasseur','Le Prince de la nuit',1);
INSERT INTO table_livres VALUES(424,'','La Lettre de l''inquisiteur','Le Prince de la nuit',2);
INSERT INTO table_livres VALUES(425,'','Pleine lune','Le Prince de la nuit',3);
INSERT INTO table_livres VALUES(426,'','Le Journal de Maximilien','Le Prince de la nuit',4);
INSERT INTO table_livres VALUES(427,'','Elise','Le Prince de la nuit',5);
INSERT INTO table_livres VALUES(428,'','Retour a Ruhenberg','Le Prince de la nuit',6);
INSERT INTO table_livres VALUES(429,'','L''empire de monsieur Joseph','Il etait une fois en France',1);
INSERT INTO table_livres VALUES(430,'','Le vol noir des corbeaux','Il etait une fois en France',2);
INSERT INTO table_livres VALUES(431,'','Honneur et Police','Il etait une fois en France',3);
INSERT INTO table_livres VALUES(432,'','Aux armes, citoyens !','Il etait une fois en France',4);
INSERT INTO table_livres VALUES(433,'','Le petit juge de Melun','Il etait une fois en France',5);
INSERT INTO table_livres VALUES(434,'','La genese','Universal war one',1);
INSERT INTO table_livres VALUES(435,'','Le fruit de la connaissance','Universal war one',2);
INSERT INTO table_livres VALUES(436,'','Caen et Abel','Universal war one',3);
INSERT INTO table_livres VALUES(437,'','Le deluge','Universal war one',4);
INSERT INTO table_livres VALUES(438,'','Le patriarche','Universal war one',6);
INSERT INTO table_livres VALUES(439,'','Babel','Universal war one',5);
INSERT INTO table_livres VALUES(440,'','Trollympiades','Trolls de Troy',11);
INSERT INTO table_livres VALUES(441,'','Les enrages du Darshan','Trolls de Troy',10);
INSERT INTO table_livres VALUES(442,'','Sang famille','Trolls de Troy',12);
INSERT INTO table_livres VALUES(443,'','L''Histoire de Waha','Trolls de Troy',14);
INSERT INTO table_livres VALUES(444,'','La guerre des gloutons II','Trolls de Troy',13);
INSERT INTO table_livres VALUES(445,'','Coffret T1 a T4 - Ex-libris Millesime 2010','Trolls de Troy',0);
INSERT INTO table_livres VALUES(446,'','Les malefices de thaumaturge','Trolls de Troy',5);
INSERT INTO table_livres VALUES(447,'','Plume de sage','Trolls de Troy',7);
INSERT INTO table_livres VALUES(448,'','Trolls dans la brume','Trolls de Troy',6);
INSERT INTO table_livres VALUES(449,'','Rock''n troll attitude','Trolls de Troy',8);
INSERT INTO table_livres VALUES(450,'','Les prisonniers du Darshan','Trolls de Troy',9);
INSERT INTO table_livres VALUES(451,'','Raids sur Rangoon','Tigres volants (les)',1);
INSERT INTO table_livres VALUES(452,'','Mission a Singapour','Tigres volants (les)',2);
INSERT INTO table_livres VALUES(453,'','Tonnerre sur le Yang-Tse','Tigres volants (les)',3);
INSERT INTO table_livres VALUES(454,'','Le treizieme prophete','Samurai',3);
INSERT INTO table_livres VALUES(455,'','Le rituel de Morinaga','Samurai',4);
INSERT INTO table_livres VALUES(456,'','L''ile sans nom','Samurai',5);
INSERT INTO table_livres VALUES(457,'','Le coeur du prophete','Samurai',1);
INSERT INTO table_livres VALUES(458,'','Les sept sources d''Akanobu','Samurai',2);
INSERT INTO table_livres VALUES(459,'','Les filles elles savent pas jouer d''abord','Noob',2);
INSERT INTO table_livres VALUES(460,'','Un jour je serai niveau 100 !','Noob',3);
INSERT INTO table_livres VALUES(461,'','Terra incognita','Naufrages d''Ythaq (les)',1);
INSERT INTO table_livres VALUES(462,'','Ophyde la Geminee','Naufrages d''Ythaq (les)',2);
INSERT INTO table_livres VALUES(463,'','L''ombre de Khengis','Naufrages d''Ythaq (les)',4);
INSERT INTO table_livres VALUES(464,'','L''ultime arcane','Naufrages d''Ythaq (les)',5);
INSERT INTO table_livres VALUES(465,'','La revolte des pions','Naufrages d''Ythaq (les)',6);
INSERT INTO table_livres VALUES(466,'','La marque des Ythes','Naufrages d''Ythaq (les)',7);
INSERT INTO table_livres VALUES(467,'','Le miroir des mensonges','Naufrages d''Ythaq (les)',8);
INSERT INTO table_livres VALUES(468,'','L''impossible verite','Naufrages d''Ythaq (les)',9);
INSERT INTO table_livres VALUES(469,'','Le Soupir des etoiles','Naufrages d''Ythaq (les)',3);
INSERT INTO table_livres VALUES(470,'','L''enfant loup','Legende',1);
INSERT INTO table_livres VALUES(471,'','Les forets profondes','Legende',2);
INSERT INTO table_livres VALUES(472,'','La grande battue','Legende',3);
INSERT INTO table_livres VALUES(473,'','Le maitre des songes','Legende',4);
INSERT INTO table_livres VALUES(474,'','Hauteterres','Legende',5);
INSERT INTO table_livres VALUES(475,'','Un, deux... Troy','Lanfeust des etoiles',1);
INSERT INTO table_livres VALUES(476,'','Les tours de Meirrion','Lanfeust des etoiles',2);
INSERT INTO table_livres VALUES(477,'','Les sables d''Abraxar','Lanfeust des etoiles',3);
INSERT INTO table_livres VALUES(478,'','Les buveurs de mondes','Lanfeust des etoiles',4);
INSERT INTO table_livres VALUES(479,'','La chevauchee des bacteries','Lanfeust des etoiles',5);
INSERT INTO table_livres VALUES(480,'','Le rale du flibustier','Lanfeust des etoiles',6);
INSERT INTO table_livres VALUES(481,'','Le secret des Dolphantes','Lanfeust des etoiles',7);
INSERT INTO table_livres VALUES(482,'','Le sang des cometes','Lanfeust des etoiles',8);
INSERT INTO table_livres VALUES(483,'','Coffret T1 a T4 - ex-libris millesime 2009','Lanfeust de Troy',1);
INSERT INTO table_livres VALUES(484,'','Coffret T5 a T8 - ex-libris millesime 2009','Lanfeust de Troy',2);
INSERT INTO table_livres VALUES(485,'','Coffret T1 a T5','Kookaburra universe',1);
INSERT INTO table_livres VALUES(486,'','Planete Dakoa','Kookaburra',1);
INSERT INTO table_livres VALUES(487,'','Secteur WBH3','Kookaburra',2);
INSERT INTO table_livres VALUES(488,'','Projet equinoxe','Kookaburra',3);
INSERT INTO table_livres VALUES(489,'','Systeme Ragnarok','Kookaburra',4);
INSERT INTO table_livres VALUES(490,'','Le bracelet de Cohars','Forets d''opale (les)',1);
INSERT INTO table_livres VALUES(491,'','L''envers du grimoire','Forets d''opale (les)',2);
INSERT INTO table_livres VALUES(492,'','La cicatrice verte','Forets d''opale (les)',3);
INSERT INTO table_livres VALUES(493,'','Les geoles de Nenuphe','Forets d''opale (les)',4);
INSERT INTO table_livres VALUES(494,'','Onze racines','Forets d''opale (les)',5);
INSERT INTO table_livres VALUES(495,'','Le sortilege du Pontife','Forets d''opale (les)',6);
INSERT INTO table_livres VALUES(496,'','Loneville','Durango',7);
INSERT INTO table_livres VALUES(497,'','Une raison pour mourir','Durango',8);
INSERT INTO table_livres VALUES(498,'','Les Chiens meurent en hiver','Durango',1);
INSERT INTO table_livres VALUES(499,'','Le Grimoire des Dieux','La Quete de l''Oiseau du Temps : Avant la Quete',2);
INSERT INTO table_livres VALUES(500,'','L''ami Javin','La Quete de l''Oiseau du Temps : Avant la Quete',1);
INSERT INTO table_livres VALUES(501,'','Integrale - Tome 1','Ribambelle',1);
INSERT INTO table_livres VALUES(502,'','Integrale - Tome 2','Ribambelle',2);
INSERT INTO table_livres VALUES(503,'','Integrale T17','Lucky Luke - Les integrales',17);
INSERT INTO table_livres VALUES(504,'','Integrale T16','Lucky Luke - Les integrales',16);
INSERT INTO table_livres VALUES(505,'','Integrale T15','Lucky Luke - Les integrales',15);
INSERT INTO table_livres VALUES(506,'','Integrale T14','Lucky Luke - Les integrales',14);
INSERT INTO table_livres VALUES(507,'','Integrale T13','Lucky Luke - Les integrales',13);
INSERT INTO table_livres VALUES(508,'','Integrale T12','Lucky Luke - Les integrales',12);
INSERT INTO table_livres VALUES(509,'','Integrale T11','Lucky Luke - Les integrales',11);
INSERT INTO table_livres VALUES(510,'','Integrale T23','Lucky Luke - Les integrales',23);
INSERT INTO table_livres VALUES(511,'','Integrale T22','Lucky Luke - Les integrales',22);
INSERT INTO table_livres VALUES(512,'','Integrale T21','Lucky Luke - Les integrales',21);
INSERT INTO table_livres VALUES(513,'','Integrale T20','Lucky Luke - Les integrales',20);
INSERT INTO table_livres VALUES(514,'','Integrale T19','Lucky Luke - Les integrales',19);
INSERT INTO table_livres VALUES(515,'','Integrale T18','Lucky Luke - Les integrales',18);
INSERT INTO table_livres VALUES(516,'','Le Flagada et pepins de peche','Flagada et pepins de peche (Le) ',2);
INSERT INTO table_livres VALUES(517,'','Le complice d''Iznogoud','Iznogoud',18);
INSERT INTO table_livres VALUES(518,'','L''anniversaire d''Iznogoud','Iznogoud',19);
INSERT INTO table_livres VALUES(519,'','Le piege de la sirene','Iznogoud',21);
INSERT INTO table_livres VALUES(520,'','Les complots du grand vizir Iznogoud','Iznogoud',2);
INSERT INTO table_livres VALUES(521,'','Les cauchemars d''Iznogoud','Iznogoud',23);
INSERT INTO table_livres VALUES(522,'','Le Grand Vizir Iznogoud','Iznogoud',1);
INSERT INTO table_livres VALUES(523,'','Qui a tue le calife?','Iznogoud',25);
INSERT INTO table_livres VALUES(524,'','le jour des fous','Iznogoud',8);
INSERT INTO table_livres VALUES(525,'','Un monstre sympathique','Iznogoud',26);
INSERT INTO table_livres VALUES(526,'','Une Carotte pour Iznogoud','Iznogoud',7);
INSERT INTO table_livres VALUES(527,'','Des Astres pour Iznogoud','Iznogoud',5);
INSERT INTO table_livres VALUES(528,'','l''infame','Iznogoud',4);
INSERT INTO table_livres VALUES(529,'','Iznogoud et les Vacances du calife','Iznogoud',3);
INSERT INTO table_livres VALUES(530,'','La tete de turc d''Iznogoud','Iznogoud',11);
INSERT INTO table_livres VALUES(531,'','L''acharne','Iznogoud',10);
INSERT INTO table_livres VALUES(532,'','Le tapis magique','Iznogoud',9);
INSERT INTO table_livres VALUES(533,'','Les cauchemars d''Iznogoud','Iznogoud',14);
INSERT INTO table_livres VALUES(534,'','Iznogoud et les femmes','Iznogoud',16);
INSERT INTO table_livres VALUES(535,'','Les cauchemars d''Iznogoud (bis)','Iznogoud',17);
INSERT INTO table_livres VALUES(536,'','Integrale T5','Barbe Rouge - Les integrales',5);
INSERT INTO table_livres VALUES(537,'','Integrale T4','Barbe Rouge - Les integrales',4);
INSERT INTO table_livres VALUES(538,'','Integrale T3','Barbe Rouge - Les integrales',3);
INSERT INTO table_livres VALUES(539,'','Integrale T2','Barbe Rouge - Les integrales',2);
INSERT INTO table_livres VALUES(540,'','Integrale T1','Barbe Rouge - Les integrales',1);
INSERT INTO table_livres VALUES(541,'','Frontiere sanglante','Marshall Blueberry',3);
INSERT INTO table_livres VALUES(542,'','Mission Sherman','Marshall Blueberry',2);
INSERT INTO table_livres VALUES(543,'','Sur ordre de Washington','Marshall Blueberry',1);
INSERT INTO table_livres VALUES(544,'','Les seigneurs de l''enfer','Percevan',7);
INSERT INTO table_livres VALUES(545,'','Les cles de feu','Percevan',6);
INSERT INTO table_livres VALUES(546,'','Le sablier d''El Jerada','Percevan',5);
INSERT INTO table_livres VALUES(547,'','Le pays d''Aslor','Percevan',4);
INSERT INTO table_livres VALUES(548,'','Les trois etoiles d''Ingaar','Percevan',1);
INSERT INTO table_livres VALUES(549,'','Le tombeau des glaces','Percevan',2);
INSERT INTO table_livres VALUES(550,'','L''epee de Ganael','Percevan',3);
INSERT INTO table_livres VALUES(551,'','Le septieme sceau','Percevan',12);
INSERT INTO table_livres VALUES(552,'','Les sceaux de l''Apocalypse','Percevan',11);
INSERT INTO table_livres VALUES(553,'','Le maitre des etoiles','Percevan',10);
INSERT INTO table_livres VALUES(554,'','L''arcantane noire','Percevan',9);
INSERT INTO table_livres VALUES(555,'','La table d''emeraude','Percevan',8);
INSERT INTO table_livres VALUES(556,'','La cite des eaux mouvantes','Valerian',1);
INSERT INTO table_livres VALUES(557,'','L''orphelin des astres','Valerian',17);
INSERT INTO table_livres VALUES(558,'','Les spectres d''inverloch','Valerian',11);
INSERT INTO table_livres VALUES(559,'','Otages de l''Ultralum','Valerian',16);
INSERT INTO table_livres VALUES(560,'','L''empire des mille planetes','Valerian',2);
INSERT INTO table_livres VALUES(561,'','Les Cercles du pouvoir','Valerian',15);
INSERT INTO table_livres VALUES(562,'','Les Armes vivantes','Valerian',14);
INSERT INTO table_livres VALUES(563,'','Sur les frontieres','Valerian',13);
INSERT INTO table_livres VALUES(564,'','Les Foudres d''Hypsis','Valerian',12);
INSERT INTO table_livres VALUES(565,'','Les Spectres d''Inverloch','Valerian',11);
INSERT INTO table_livres VALUES(566,'','Brooklyn station, Terminus Cosmos','Valerian',10);
INSERT INTO table_livres VALUES(567,'','Metro Chatelet, direction Cassiopee','Valerian',9);
INSERT INTO table_livres VALUES(568,'','Les heros de l''equinoxe','Valerian',8);
INSERT INTO table_livres VALUES(569,'','Les terres truquees','Valerian',7);
INSERT INTO table_livres VALUES(570,'','L''ambassadeur des ombres','Valerian',6);
INSERT INTO table_livres VALUES(571,'','Les oiseaux du maitre','Valerian',5);
INSERT INTO table_livres VALUES(572,'','L''ouvre Temps','Valerian',21);
INSERT INTO table_livres VALUES(573,'','Bienvenue sur Alflolol','Valerian',4);
INSERT INTO table_livres VALUES(574,'','L''ordre des Pierres','Valerian',20);
INSERT INTO table_livres VALUES(575,'','le pays sans etoile','Valerian',3);
INSERT INTO table_livres VALUES(576,'','Au bord du Grand Rien','Valerian',19);
INSERT INTO table_livres VALUES(577,'','L''empire des mille planetes','Valerian',2);
INSERT INTO table_livres VALUES(578,'','Par des temps incertains','Valerian',18);
INSERT INTO table_livres VALUES(579,'','La marque du diable','Le Scorpion ',1);
INSERT INTO table_livres VALUES(580,'','Le secret du Pape','Le Scorpion ',2);
INSERT INTO table_livres VALUES(581,'','La croix de Pierre','Le Scorpion ',3);
INSERT INTO table_livres VALUES(582,'','La vallee sacree','Le Scorpion ',5);
INSERT INTO table_livres VALUES(583,'','Le demon au Vatican','Le Scorpion ',4);
INSERT INTO table_livres VALUES(584,'','Au nom du pere','Le Scorpion ',7);
INSERT INTO table_livres VALUES(585,'','Le tresor du temple','Le Scorpion ',6);
INSERT INTO table_livres VALUES(586,'','L''ombre de l''ange','Le Scorpion ',8);
INSERT INTO table_livres VALUES(587,'','Le masque de la verite','Le Scorpion ',9);
INSERT INTO table_livres VALUES(588,'','Black Op','Black Op',6);
INSERT INTO table_livres VALUES(589,'','Black Op','Black Op',5);
INSERT INTO table_livres VALUES(590,'','Black Op','Black Op',4);
INSERT INTO table_livres VALUES(591,'','Black Op','Black Op',3);
INSERT INTO table_livres VALUES(592,'','Black Op','Black Op',2);
INSERT INTO table_livres VALUES(593,'','Black Op','Black Op',1);
INSERT INTO table_livres VALUES(594,'','Black Op','Black Op',6);
INSERT INTO table_livres VALUES(595,'','L''ermite et le nid','Merlin',6);
INSERT INTO table_livres VALUES(596,'','Le chaudron de Bran le beni','Merlin',7);
INSERT INTO table_livres VALUES(597,'','Quelque part entre les ombres','Blacksad',1);
INSERT INTO table_livres VALUES(598,'','Arctic-Nation','Blacksad',2);
INSERT INTO table_livres VALUES(599,'','Ame rouge','Blacksad',3);
INSERT INTO table_livres VALUES(600,'','L''enfer, le silence','Blacksad',4);
INSERT INTO table_livres VALUES(601,'','Un yankee nomme Blueberry','Jeunesse de Blueberry',2);
INSERT INTO table_livres VALUES(602,'','L''aigle solitaire','Blueberry',3);
INSERT INTO table_livres VALUES(603,'','Nez casse','Blueberry',18);
INSERT INTO table_livres VALUES(604,'','Le cavalier perdu','Blueberry',4);
INSERT INTO table_livres VALUES(605,'','La lLongue marche','Blueberry',19);
INSERT INTO table_livres VALUES(607,'','La tribu fantome','Blueberry',20);
INSERT INTO table_livres VALUES(608,'','Le bout de la piste','Blueberry',22);
INSERT INTO table_livres VALUES(609,'','La piste des Navajos','Blueberry',5);
INSERT INTO table_livres VALUES(610,'','La derniere carte','Blueberry',21);
INSERT INTO table_livres VALUES(611,'','Arizona Love','Blueberry',23);
INSERT INTO table_livres VALUES(612,'','L''homme a l''etoile d''argent','Blueberry',6);
INSERT INTO table_livres VALUES(613,'','Mister Blueberry','Blueberry',24);
INSERT INTO table_livres VALUES(614,'','Le cheval de fer','Blueberry',7);
INSERT INTO table_livres VALUES(615,'','Ombres sur Tombstone','Blueberry',25);
INSERT INTO table_livres VALUES(616,'','L''homme aux poings d''acier','Blueberry',8);
INSERT INTO table_livres VALUES(617,'','Geronimo l''apache','Blueberry',26);
INSERT INTO table_livres VALUES(618,'','Dust','Blueberry',28);
INSERT INTO table_livres VALUES(619,'','La piste des sioux','Blueberry',9);
INSERT INTO table_livres VALUES(620,'','Le general tete jaune','Blueberry',10);
INSERT INTO table_livres VALUES(621,'','La mine de l''Allemand perdu','Blueberry',11);
INSERT INTO table_livres VALUES(622,'','Le spectre aux balles d''or','Blueberry',12);
INSERT INTO table_livres VALUES(623,'','O.K. Corral','Blueberry',27);
INSERT INTO table_livres VALUES(624,'','Chihuahua Pearl','Blueberry',13);
INSERT INTO table_livres VALUES(625,'','L''homme qui valait 500.000$','Blueberry',14);
INSERT INTO table_livres VALUES(626,'','Ballade pour un cercueil','Blueberry',15);
INSERT INTO table_livres VALUES(627,'','Fort Navajo','Blueberry',1);
INSERT INTO table_livres VALUES(628,'','Angel Face','Blueberry',17);
INSERT INTO table_livres VALUES(629,'','Tonnerre a l''ouest','Blueberry',2);
INSERT INTO table_livres VALUES(630,'','Le Hors-la-loi','Blueberry',16);
INSERT INTO table_livres VALUES(631,'','La nuit des aigles','Wayne Shelton',8);
INSERT INTO table_livres VALUES(632,'','La lance de Longinus','Wayne Shelton',7);
INSERT INTO table_livres VALUES(633,'','L''otage','Wayne Shelton',6);
INSERT INTO table_livres VALUES(634,'','La vengeance','Wayne Shelton',5);
INSERT INTO table_livres VALUES(635,'','Le survivant','Wayne Shelton',4);
INSERT INTO table_livres VALUES(636,'','Le contrat','Wayne Shelton',3);
INSERT INTO table_livres VALUES(637,'','La mission','Wayne Shelton',1);
INSERT INTO table_livres VALUES(638,'','Son altesse Honesty !','Wayne Shelton',9);
INSERT INTO table_livres VALUES(639,'','La trahison','Wayne Shelton',2);
INSERT INTO table_livres VALUES(640,'','Le diamant d''Abraham','Eternels ',3);
INSERT INTO table_livres VALUES(641,'','Mira','Eternels ',2);
INSERT INTO table_livres VALUES(642,'','Uma','Eternels ',1);
INSERT INTO table_livres VALUES(643,'','Le Puits des tenebres','Eternels ',4);
INSERT INTO table_livres VALUES(644,'','L''Oeuf des tenebres','La Quete de l''Oiseau du Temps ',4);
INSERT INTO table_livres VALUES(645,'','Le Rige','La Quete de l''Oiseau du Temps ',3);
INSERT INTO table_livres VALUES(646,'','Le Temple de l''oubli','La Quete de l''Oiseau du Temps ',2);
INSERT INTO table_livres VALUES(647,'','Conque de  Conque de Ramor','La Quete de l''Oiseau du Temps ',1);
INSERT INTO table_livres VALUES(648,'','Integrale T3 - Le Livre de Soufre','Mic Mac Adam',3);
INSERT INTO table_livres VALUES(649,'','Integrale T2 - Le livre de sang','Mic Mac Adam',2);
INSERT INTO table_livres VALUES(650,'','Integrale T1 - Le Livre noir','Mic Mac Adam',1);
INSERT INTO table_livres VALUES(651,'','Le Piege','Tramp',1);
INSERT INTO table_livres VALUES(652,'','Le Bras de fer','Tramp',2);
INSERT INTO table_livres VALUES(653,'','Le Bateau assassine','Tramp',3);
INSERT INTO table_livres VALUES(654,'','Pour Helene','Tramp',4);
INSERT INTO table_livres VALUES(655,'','Les sept nains','Berlin',1);
INSERT INTO table_livres VALUES(656,'','Le Cycle de l''eau I','Okko',1);
INSERT INTO table_livres VALUES(657,'','Le Cycle de la terre I','Okko',3);
INSERT INTO table_livres VALUES(658,'','Le Cycle de la terre II','Okko',4);
INSERT INTO table_livres VALUES(659,'','Le Cycle de l''air I','Okko',5);
INSERT INTO table_livres VALUES(660,'','Le Cycle de l''eau II','Okko',2);
INSERT INTO table_livres VALUES(661,'','Le cycle de l''air II','Okko',6);
INSERT INTO table_livres VALUES(662,'','Le Cycle du feu I','Okko',7);
INSERT INTO table_livres VALUES(663,'','edition anniversaire 02. Planete bleue','Aquablue',2);
INSERT INTO table_livres VALUES(664,'','edition anniversaire 01. Nao - Ultimate edition','Aquablue',1);
INSERT INTO table_livres VALUES(665,'','edition anniversaire 09. Le Totem des Cynos','Aquablue',9);
INSERT INTO table_livres VALUES(666,'','edition anniversaire 08. Fondation Aquablue','Aquablue',8);
INSERT INTO table_livres VALUES(667,'','edition anniversaire 07. etoile Blanche - 2e partie','Aquablue',7);
INSERT INTO table_livres VALUES(668,'','edition anniversaire 06. etoile Blanche - 1re partie','Aquablue',6);
INSERT INTO table_livres VALUES(669,'','edition anniversaire 05. Projet Atalanta','Aquablue',5);
INSERT INTO table_livres VALUES(670,'','edition anniversaire 04. Corail noir','Aquablue',4);
INSERT INTO table_livres VALUES(671,'','edition anniversaire 03. Le Megophias','Aquablue',3);
INSERT INTO table_livres VALUES(672,'','Chaud et froid pour les Gorilles','Tout Sammy',5);
INSERT INTO table_livres VALUES(673,'','Drole de cirque pour les Gorilles','Tout Sammy',7);
INSERT INTO table_livres VALUES(674,'','Les Gorilles entre Klan et Vatican','Tout Sammy',6);
INSERT INTO table_livres VALUES(675,'','Les Gorilles reviennent de loin','Tout Sammy',8);
INSERT INTO table_livres VALUES(676,'','Les Gorilles aux abois','Tout Sammy',9);
INSERT INTO table_livres VALUES(677,'','Quatuor pour Gorilles','Tout Sammy',10);
INSERT INTO table_livres VALUES(678,'','Les Gorilles vous saluent bien','Tout Sammy',1);
INSERT INTO table_livres VALUES(679,'','Des balles, des filles et des Gorilles','Tout Sammy',3);
INSERT INTO table_livres VALUES(680,'','Salades exotiques pour les Gorilles','Tout Sammy',2);
INSERT INTO table_livres VALUES(681,'','Gorilles, canines et dents de lait','Tout Sammy',4);
INSERT INTO table_livres VALUES(682,'','Special','Tout Lucky Luke',10);
INSERT INTO table_livres VALUES(683,'','Special','Tout Lucky Luke',1);
INSERT INTO table_livres VALUES(684,'','Special','Tout Lucky Luke',2);
INSERT INTO table_livres VALUES(685,'','Special','Tout Lucky Luke',3);
INSERT INTO table_livres VALUES(686,'','Special','Tout Lucky Luke',4);
INSERT INTO table_livres VALUES(687,'','Special','Tout Lucky Luke',5);
INSERT INTO table_livres VALUES(688,'','Special','Tout Lucky Luke',6);
INSERT INTO table_livres VALUES(689,'','Special','Tout Lucky Luke',7);
INSERT INTO table_livres VALUES(690,'','Special','Tout Lucky Luke',8);
INSERT INTO table_livres VALUES(691,'','Special','Tout Lucky Luke',9);
INSERT INTO table_livres VALUES(692,'','Aventures exotiques','Tout Gil Jourdan/Tout Cesar',3);
INSERT INTO table_livres VALUES(693,'','Dix aventures','Tout Gil Jourdan/Tout Cesar',4);
INSERT INTO table_livres VALUES(694,'','Duo pour un heros','Tout Gil Jourdan/Tout Cesar',5);
INSERT INTO table_livres VALUES(695,'','Enquetes francaises','Tout Gil Jourdan/Tout Cesar',2);
INSERT INTO table_livres VALUES(696,'','Premieres aventures','Tout Gil Jourdan/Tout Cesar',1);
INSERT INTO table_livres VALUES(697,'','Trois detectives','Tout Gil Jourdan/Tout Cesar',6);
INSERT INTO table_livres VALUES(698,'','De l''Extreme-Nord a l''Extreme-Orient','Tout Buck Danny',6);
INSERT INTO table_livres VALUES(699,'','Vols vers l''inconnu','Tout Buck Danny',7);
INSERT INTO table_livres VALUES(700,'','Pilotes de prototypes','Tout Buck Danny',8);
INSERT INTO table_livres VALUES(701,'','Le Retour des Tigres Volants','Tout Buck Danny',9);
INSERT INTO table_livres VALUES(702,'','Missions "top secret"','Tout Buck Danny',10);
INSERT INTO table_livres VALUES(703,'','Missions a tres haut risque','Tout Buck Danny',11);
INSERT INTO table_livres VALUES(704,'','Mission aerienne anti-mafia','Tout Buck Danny',12);
INSERT INTO table_livres VALUES(705,'','Alerte nucleaire','Tout Buck Danny',13);
INSERT INTO table_livres VALUES(706,'','Ennemis interieurs','Tout Buck Danny',14);
INSERT INTO table_livres VALUES(707,'','Zones de combat','Tout Buck Danny',15);
INSERT INTO table_livres VALUES(708,'','La Guerre du Pacifique (premiere partie)','Tout Buck Danny',1);
INSERT INTO table_livres VALUES(709,'','La Guerre du Pacifique (deuxieme partie)','Tout Buck Danny',2);
INSERT INTO table_livres VALUES(710,'','Les Aviateurs demobilises','Tout Buck Danny',3);
INSERT INTO table_livres VALUES(711,'','La Guerre de Coree','Tout Buck Danny',4);
INSERT INTO table_livres VALUES(712,'','Pilotes de porte-avions','Tout Buck Danny',5);
INSERT INTO table_livres VALUES(713,'','Echec aux mystificateurs','Tif et Tondu - L''integrale',4);
INSERT INTO table_livres VALUES(714,'','Enquetes a travers le monde','Tif et Tondu - L''integrale',7);
INSERT INTO table_livres VALUES(715,'','Sur la piste du crime','Tif et Tondu - L''integrale',2);
INSERT INTO table_livres VALUES(716,'','Capitaine Steene','Theodore Poussin',1);
INSERT INTO table_livres VALUES(717,'','Le Mangeur d''archipels','Theodore Poussin',2);
INSERT INTO table_livres VALUES(718,'','Marie Verite','Theodore Poussin',3);
INSERT INTO table_livres VALUES(719,'','Secrets','Theodore Poussin',4);
INSERT INTO table_livres VALUES(720,'','Le Tresor du Rajah blanc','Theodore Poussin',5);
INSERT INTO table_livres VALUES(721,'','Un passager porte disparu','Theodore Poussin',6);
INSERT INTO table_livres VALUES(722,'','La Vallee des roses','Theodore Poussin',7);
INSERT INTO table_livres VALUES(723,'','La Maison dans l''ile','Theodore Poussin',8);
INSERT INTO table_livres VALUES(724,'','La Terrasse des audiences, tome 1','Theodore Poussin',9);
INSERT INTO table_livres VALUES(725,'','La Terrasse des audiences, tome 2','Theodore Poussin',10);
INSERT INTO table_livres VALUES(726,'','Novembre toute l''annee','Theodore Poussin',11);
INSERT INTO table_livres VALUES(727,'','Les Jalousies','Theodore Poussin',12);
INSERT INTO table_livres VALUES(728,'','L''Heritage','Spirou et Fantasio - Hors serie',1);
INSERT INTO table_livres VALUES(729,'','Radar le robot','Spirou et Fantasio - Hors serie',2);
INSERT INTO table_livres VALUES(730,'','Le Dictateur et le champignon','Spirou et Fantasio',7);
INSERT INTO table_livres VALUES(731,'','Du glucose pour Noemie','Spirou et Fantasio',21);
INSERT INTO table_livres VALUES(732,'','La Corne du rhinoceros','Spirou et Fantasio',6);
INSERT INTO table_livres VALUES(733,'','Tora-Torapa','Spirou et Fantasio',23);
INSERT INTO table_livres VALUES(734,'','La Mauvaise tete','Spirou et Fantasio',8);
INSERT INTO table_livres VALUES(735,'','Tembo Tabou','Spirou et Fantasio',24);
INSERT INTO table_livres VALUES(736,'','Les Pirates du silence','Spirou et Fantasio',10);
INSERT INTO table_livres VALUES(737,'','Du cidre pour les etoiles','Spirou et Fantasio',26);
INSERT INTO table_livres VALUES(738,'','Le Repaire de la murene','Spirou et Fantasio',9);
INSERT INTO table_livres VALUES(739,'','Le Gri-gri du Niokolo-koba','Spirou et Fantasio',25);
INSERT INTO table_livres VALUES(740,'','Le Gorille a bonne mine','Spirou et Fantasio',11);
INSERT INTO table_livres VALUES(741,'','L''Ankou','Spirou et Fantasio',27);
INSERT INTO table_livres VALUES(742,'','Le nid des marsupilamis','Spirou et Fantasio',12);
INSERT INTO table_livres VALUES(743,'','Kodo, le Tyran','Spirou et Fantasio',28);
INSERT INTO table_livres VALUES(744,'','Le Nid des Marsupilamis','Spirou et Fantasio',12);
INSERT INTO table_livres VALUES(745,'','Des haricots partout','Spirou et Fantasio',29);
INSERT INTO table_livres VALUES(746,'','Le Voyageur du Mesozoaique','Spirou et Fantasio',13);
INSERT INTO table_livres VALUES(747,'','La Boite noire','Spirou et Fantasio',31);
INSERT INTO table_livres VALUES(748,'','Z comme Zorglub','Spirou et Fantasio',15);
INSERT INTO table_livres VALUES(749,'','Les Faiseurs de silence','Spirou et Fantasio',32);
INSERT INTO table_livres VALUES(750,'','Le Prisonnier du bouddha','Spirou et Fantasio',14);
INSERT INTO table_livres VALUES(751,'','Virus','Spirou et Fantasio',33);
INSERT INTO table_livres VALUES(752,'','4 aventures de Spirou et Fantasio','Spirou et Fantasio',1);
INSERT INTO table_livres VALUES(753,'','L''Ombre du Z','Spirou et Fantasio',16);
INSERT INTO table_livres VALUES(754,'','Aventure en Australie','Spirou et Fantasio',34);
INSERT INTO table_livres VALUES(755,'','Il y a un sorcier a Champignac','Spirou et Fantasio',2);
INSERT INTO table_livres VALUES(756,'','QRN sur Bretzelburg','Spirou et Fantasio',18);
INSERT INTO table_livres VALUES(757,'','Spirou et les heritiers','Spirou et Fantasio',4);
INSERT INTO table_livres VALUES(758,'','Panade a Champignac','Spirou et Fantasio',19);
INSERT INTO table_livres VALUES(759,'','Les Chapeaux noirs','Spirou et Fantasio',3);
INSERT INTO table_livres VALUES(760,'','Le Faiseur d''or','Spirou et Fantasio',20);
INSERT INTO table_livres VALUES(761,'','Les Voleurs du Marsupilami','Spirou et Fantasio',5);
INSERT INTO table_livres VALUES(762,'','L''Abbaye truquee','Spirou et Fantasio',22);
INSERT INTO table_livres VALUES(763,'','Dieu seul le sait','Soda',10);
INSERT INTO table_livres VALUES(764,'','Prieres et balistique','Soda',11);
INSERT INTO table_livres VALUES(765,'','Un ange trepasse','Soda',1);
INSERT INTO table_livres VALUES(766,'','Lettres a Satan','Soda',2);
INSERT INTO table_livres VALUES(767,'','Tu ne buteras point','Soda',3);
INSERT INTO table_livres VALUES(768,'','Dieu est mort ce soir','Soda',4);
INSERT INTO table_livres VALUES(769,'','Fureur chez les saints','Soda',5);
INSERT INTO table_livres VALUES(770,'','Leve-toi et meurs','Soda',7);
INSERT INTO table_livres VALUES(771,'','Confession express','Soda',6);
INSERT INTO table_livres VALUES(772,'','Et delivre-nous du mal','Soda',9);
INSERT INTO table_livres VALUES(773,'','La disparition','Seuls',1);
INSERT INTO table_livres VALUES(774,'','Le maitre des couteaux','Seuls',2);
INSERT INTO table_livres VALUES(775,'','Le clan du requin','Seuls',3);
INSERT INTO table_livres VALUES(776,'','Les Cairns rouges','Seuls',4);
INSERT INTO table_livres VALUES(777,'','La Soupe aux Schtroumpfs','Les Schtroumpfs',10);
INSERT INTO table_livres VALUES(778,'','olympiques','Les Schtroumpfs',11);
INSERT INTO table_livres VALUES(779,'','Le Bebe Schtroumpf','Les Schtroumpfs',12);
INSERT INTO table_livres VALUES(780,'','Les P''tits Schtroumpfs','Les Schtroumpfs',13);
INSERT INTO table_livres VALUES(781,'','L''etrange reveil du Schtroumpf paresseux','Les Schtroumpfs',15);
INSERT INTO table_livres VALUES(782,'','Le Schtroumpf noir','Les Schtroumpfs',1);
INSERT INTO table_livres VALUES(783,'','Le Schtroumpfissime','Les Schtroumpfs',2);
INSERT INTO table_livres VALUES(784,'','La Schtroumpfette','Les Schtroumpfs',3);
INSERT INTO table_livres VALUES(785,'','L''Oeuf et les Schtroumpfs','Les Schtroumpfs',4);
INSERT INTO table_livres VALUES(786,'','Les Schtroumpfs et le Cracoucass','Les Schtroumpfs',5);
INSERT INTO table_livres VALUES(787,'','Le Cosmoschtroumpf','Les Schtroumpfs',6);
INSERT INTO table_livres VALUES(788,'','L''Apprenti Schtroumpf','Les Schtroumpfs',7);
INSERT INTO table_livres VALUES(789,'','Histoires de Schtroumpfs','Les Schtroumpfs',8);
INSERT INTO table_livres VALUES(790,'','Schtroumpf vert et vert Schtroumpf','Les Schtroumpfs',9);
INSERT INTO table_livres VALUES(791,'','Mae West','Sammy',34);
INSERT INTO table_livres VALUES(792,'','Boy','Sammy',40);
INSERT INTO table_livres VALUES(793,'','Un Gorille en cage','Sammy',33);
INSERT INTO table_livres VALUES(794,'','Pepee flingueuse','Sammy',39);
INSERT INTO table_livres VALUES(795,'','Deux gorilles a Paris','Sammy',38);
INSERT INTO table_livres VALUES(796,'','Lady O''','Sammy',37);
INSERT INTO table_livres VALUES(797,'','Les Gorilles menent la danse','Sammy',35);
INSERT INTO table_livres VALUES(798,'','1970-1973','Les Petits Hommes - L''integrale',2);
INSERT INTO table_livres VALUES(799,'','1967-1970','Les Petits Hommes - L''integrale',1);
INSERT INTO table_livres VALUES(800,'','Tu veux mon doigt ?','Le Petit Spirou',2);
INSERT INTO table_livres VALUES(801,'','C''est pour ton bien !','Le Petit Spirou',4);
INSERT INTO table_livres VALUES(802,'','N''oublie pas ta capuche !','Le Petit Spirou',6);
INSERT INTO table_livres VALUES(803,'','"Merci" qui ?','Le Petit Spirou',5);
INSERT INTO table_livres VALUES(804,'','Demande a ton pere !','Le Petit Spirou',7);
INSERT INTO table_livres VALUES(805,'','C''est pas de ton age !','Le Petit Spirou',9);
INSERT INTO table_livres VALUES(806,'','Tu comprendras quand tu s''ras grand !','Le Petit Spirou',10);
INSERT INTO table_livres VALUES(807,'','Tu ne s''ras jamais grand !','Le Petit Spirou',11);
INSERT INTO table_livres VALUES(808,'','Fais de beaux reves','Le Petit Spirou',13);
INSERT INTO table_livres VALUES(809,'','C''est du joli!','Le Petit Spirou',12);
INSERT INTO table_livres VALUES(810,'','Bien fait pour toi !','Le Petit Spirou',14);
INSERT INTO table_livres VALUES(811,'','Dis bonjour a la dame!','Le Petit Spirou',1);
INSERT INTO table_livres VALUES(812,'','Mais ! Qu''est-ce que tu fabriques ?','Le Petit Spirou',3);
INSERT INTO table_livres VALUES(813,'','Natacha et le maharadjah','Natacha',2);
INSERT INTO table_livres VALUES(814,'','La Memoire de metal','Natacha',3);
INSERT INTO table_livres VALUES(815,'','L''ange blond','Natacha',16);
INSERT INTO table_livres VALUES(816,'','Un trone pour Natacha','Natacha',4);
INSERT INTO table_livres VALUES(817,'','Double vol','Natacha',5);
INSERT INTO table_livres VALUES(818,'','Le Treizieme apotre','Natacha',6);
INSERT INTO table_livres VALUES(819,'','L''Hotesse et Monna Lisa','Natacha',7);
INSERT INTO table_livres VALUES(820,'','Instantanes pour Caltech','Natacha',8);
INSERT INTO table_livres VALUES(821,'','Les Machines incertaines','Natacha',9);
INSERT INTO table_livres VALUES(822,'','L''ile d''outre-monde','Natacha',10);
INSERT INTO table_livres VALUES(823,'','Le Grand pari','Natacha',11);
INSERT INTO table_livres VALUES(824,'','Les Culottes de fer','Natacha',12);
INSERT INTO table_livres VALUES(825,'','Les Nomades du ciel','Natacha',13);
INSERT INTO table_livres VALUES(826,'','Cauchemirage','Natacha',14);
INSERT INTO table_livres VALUES(827,'','La ceinture de Cherchemidi','Natacha',15);
INSERT INTO table_livres VALUES(828,'','Natacha, hotesse de l''air','Natacha',1);
INSERT INTO table_livres VALUES(829,'','L''Heure du tigre','Largo Winch',8);
INSERT INTO table_livres VALUES(830,'','Voir Venise...','Largo Winch',9);
INSERT INTO table_livres VALUES(831,'','... Et mourir','Largo Winch',10);
INSERT INTO table_livres VALUES(832,'','Golden Gate','Largo Winch',11);
INSERT INTO table_livres VALUES(833,'','Shadow','Largo Winch',12);
INSERT INTO table_livres VALUES(834,'','Le Prix de l''argent','Largo Winch',13);
INSERT INTO table_livres VALUES(835,'','La voie et la vertu','Largo Winch',16);
INSERT INTO table_livres VALUES(836,'','Mer noire','Largo Winch',17);
INSERT INTO table_livres VALUES(837,'','L''Heritier','Largo Winch',1);
INSERT INTO table_livres VALUES(838,'','Les trois yeux des gardiens du Tao','Largo Winch',15);
INSERT INTO table_livres VALUES(839,'','Le Groupe W','Largo Winch',2);
INSERT INTO table_livres VALUES(840,'','La loi du dollar','Largo Winch',14);
INSERT INTO table_livres VALUES(841,'','O.P.A.','Largo Winch',3);
INSERT INTO table_livres VALUES(842,'','Business Blues','Largo Winch',4);
INSERT INTO table_livres VALUES(843,'','H','Largo Winch',5);
INSERT INTO table_livres VALUES(844,'','Dutch Connection','Largo Winch',6);
INSERT INTO table_livres VALUES(845,'','La Forteresse de Makiling','Largo Winch',7);
INSERT INTO table_livres VALUES(846,'','Sous le regard de la lune','Kogaratsu',8);
INSERT INTO table_livres VALUES(847,'','Fournaise','Kogaratsu',11);
INSERT INTO table_livres VALUES(848,'','Le protocole du Mal','Kogaratsu',12);
INSERT INTO table_livres VALUES(849,'','La strategie des phalenes','Kogaratsu',9);
INSERT INTO table_livres VALUES(850,'','Rouge ultime','Kogaratsu',10);
INSERT INTO table_livres VALUES(851,'','Le Pont de nulle part','Kogaratsu',0);
INSERT INTO table_livres VALUES(852,'','Le Mon au lotus de sang','Kogaratsu',1);
INSERT INTO table_livres VALUES(853,'','Le Tresor des etas','Kogaratsu',2);
INSERT INTO table_livres VALUES(854,'','Le Printemps ecartele','Kogaratsu',3);
INSERT INTO table_livres VALUES(855,'','Le Dos du tigre','Kogaratsu',4);
INSERT INTO table_livres VALUES(856,'','Par-dela les cendres','Kogaratsu',5);
INSERT INTO table_livres VALUES(857,'','L''Homme sur la vague','Kogaratsu',6);
INSERT INTO table_livres VALUES(858,'','L''Autre moitie du ciel','Kogaratsu',7);
INSERT INTO table_livres VALUES(859,'','La Flute a 6 schtroumpfs','Johan et Pirlouit',9);
INSERT INTO table_livres VALUES(860,'','La Guerre des sept fontaines','Johan et Pirlouit',10);
INSERT INTO table_livres VALUES(861,'','L''Anneau des Castellac','Johan et Pirlouit',11);
INSERT INTO table_livres VALUES(862,'','Le Pays maudit','Johan et Pirlouit',12);
INSERT INTO table_livres VALUES(863,'','Le Sortilege de Maltrochu','Johan et Pirlouit',13);
INSERT INTO table_livres VALUES(864,'','La nuit des sorciers','Johan et Pirlouit',16);
INSERT INTO table_livres VALUES(865,'','Les troubadours de Roc-a -Pic','Johan et Pirlouit',15);
INSERT INTO table_livres VALUES(866,'','La horde du corbeau','Johan et Pirlouit',14);
INSERT INTO table_livres VALUES(867,'','Le Chatiment de Basenhau','Johan et Pirlouit',1);
INSERT INTO table_livres VALUES(868,'','Le serment des vikings','Johan et Pirlouit',5);
INSERT INTO table_livres VALUES(869,'','Le Maitre de Roucybeuf','Johan et Pirlouit',2);
INSERT INTO table_livres VALUES(870,'','Le Lutin du bois aux roches','Johan et Pirlouit',3);
INSERT INTO table_livres VALUES(871,'','La Pierre de lune','Johan et Pirlouit',4);
INSERT INTO table_livres VALUES(872,'','Le Serment des vikings','Johan et Pirlouit',5);
INSERT INTO table_livres VALUES(873,'','La Source des dieux','Johan et Pirlouit',6);
INSERT INTO table_livres VALUES(874,'','La Fleche noire','Johan et Pirlouit',7);
INSERT INTO table_livres VALUES(875,'','Le Sire de Montresor','Johan et Pirlouit',8);
INSERT INTO table_livres VALUES(876,'','Zelda','Jerome K. Jerome Bloche',6);
INSERT INTO table_livres VALUES(877,'','Le Jeu de trois','Jerome K. Jerome Bloche',5);
INSERT INTO table_livres VALUES(878,'','Un fauve en cage','Jerome K. Jerome Bloche',14);
INSERT INTO table_livres VALUES(879,'','Le Gabion','Jerome K. Jerome Bloche',12);
INSERT INTO table_livres VALUES(880,'','Un oiseau pour le chat','Jerome K. Jerome Bloche',7);
INSERT INTO table_livres VALUES(881,'','Le cas Lagaffe','Gaston Lagaffe',12);
INSERT INTO table_livres VALUES(882,'','Gaffes, bevues et boulettes','Gaston Lagaffe',14);
INSERT INTO table_livres VALUES(883,'','Le gang des gaffeurs','Gaston Lagaffe',15);
INSERT INTO table_livres VALUES(884,'','La saga des gaffes','Gaston Lagaffe',17);
INSERT INTO table_livres VALUES(885,'','Lagaffe merite des baffes','Gaston Lagaffe',16);
INSERT INTO table_livres VALUES(886,'','Les archives de la gaffe','Gaston Lagaffe',1);
INSERT INTO table_livres VALUES(887,'','Les gaffes d''un gars gonfle','Gaston Lagaffe',3);
INSERT INTO table_livres VALUES(888,'','Gaffes a gogo','Gaston Lagaffe',2);
INSERT INTO table_livres VALUES(889,'','Gala de gaffes','Gaston Lagaffe',4);
INSERT INTO table_livres VALUES(890,'','Le bureau des gaffes en gros','Gaston Lagaffe',5);
INSERT INTO table_livres VALUES(891,'','Gare aux gaffes','Gaston Lagaffe',6);
INSERT INTO table_livres VALUES(892,'','Rafales de gaffes','Gaston Lagaffe',8);
INSERT INTO table_livres VALUES(893,'','Un gaffeur sachant gaffer','Gaston Lagaffe',9);
INSERT INTO table_livres VALUES(894,'','Lagaffe nous gate','Gaston Lagaffe',10);
INSERT INTO table_livres VALUES(895,'','Le repos du gaffeur','Gaston Lagaffe',11);
INSERT INTO table_livres VALUES(896,'','Le geant de la gaffe','Gaston Lagaffe',13);
INSERT INTO table_livres VALUES(897,'','Classes de neige','Cedric',2);
INSERT INTO table_livres VALUES(898,'','Comme sur des roulettes','Cedric',8);
INSERT INTO table_livres VALUES(899,'','Parasite sur canape','Cedric',9);
INSERT INTO table_livres VALUES(900,'','Cygne d''etang','Cedric',11);
INSERT INTO table_livres VALUES(901,'','Terrain minets','Cedric',12);
INSERT INTO table_livres VALUES(902,'','Les Baleines publiques','Broussaille',1);
INSERT INTO table_livres VALUES(903,'','Les Sculpteurs de lumiere','Broussaille',2);
INSERT INTO table_livres VALUES(904,'','Bill, chien modele','Boule et Bill',10);
INSERT INTO table_livres VALUES(905,'','Bill de match','Boule et Bill',11);
INSERT INTO table_livres VALUES(906,'','Une vie de chien','Boule et Bill',9);
INSERT INTO table_livres VALUES(907,'','Le Noye a deux tetes','Adele Blanc-Sec',6);
INSERT INTO table_livres VALUES(908,'','O Dingos, O Chateaux','Tardi',0);
INSERT INTO table_livres VALUES(909,'','Une gueule de bois en plomb','Nestor Burma',0);
INSERT INTO table_livres VALUES(910,'','Un oiseau pour le chat','Jerome K. Jerome Bloche',7);
INSERT INTO table_livres VALUES(911,'','Le Dernier envol','aviation',0);
INSERT INTO table_livres VALUES(912,'','T''as qu''a t''retenir !','Le Petit Spirou',8);
INSERT INTO table_livres VALUES(913,'','Le Savant Fou','Adele Blanc-Sec',3);
INSERT INTO table_livres VALUES(914,'','Momies en Folie','Adele Blanc-Sec',4);
INSERT INTO table_livres VALUES(915,'','Le Secret de la Salamandre','Adele Blanc-Sec',5);
INSERT INTO table_livres VALUES(916,'','Tous des Monstres !','Adele Blanc-Sec',7);
INSERT INTO table_livres VALUES(917,'','Le mystere des Profondeurs','Adele Blanc-Sec',8);
INSERT INTO table_livres VALUES(918,'','La voie du Rige','La Quete de l''Oiseau du Temps : Avant la Quete',3);
INSERT INTO table_livres VALUES(919,'2-205-01264-9','Chlorophylle et les conspirateurs','Chlorophylle',1);
INSERT INTO table_livres VALUES(920,'2-205-01264-9','Pas de salami pour Celimene','Chlorophylle',2);
INSERT INTO table_livres VALUES(921,'2-205-01556-7','Chlorophylle contre les rats noirs','Chlorophylle',3);
INSERT INTO table_livres VALUES(922,'2-205-01738-1','Les croquillards','Chlorophylle',4);
INSERT INTO table_livres VALUES(923,'','Zizanion le terrible','Chlorophylle',5);
INSERT INTO table_livres VALUES(924,'','Integrale 3','Integrale Bernard Prince',3);
INSERT INTO table_livres VALUES(925,'','Le diabolique M. Choc','Tif et Tondu - L''integrale',1);
INSERT INTO table_livres VALUES(926,'','Signe M. Choc','Tif et Tondu - L''integrale',3);
INSERT INTO table_livres VALUES(927,'','Choc mene la danse','Tif et Tondu - L''integrale',5);
INSERT INTO table_livres VALUES(928,'','Horizons lointains','Tif et Tondu - L''integrale',6);
INSERT INTO table_livres VALUES(929,'','Pauvre Lampil','Pauvre Lampil',1);
INSERT INTO table_livres VALUES(930,'','Pauvre Lampil','Pauvre Lampil',2);
INSERT INTO table_livres VALUES(931,'','Pauvre Lampil','Pauvre Lampil',3);
INSERT INTO table_livres VALUES(932,'','Pauvre Lampil','Pauvre Lampil',4);
INSERT INTO table_livres VALUES(933,'','Pauvre Lampil','Pauvre Lampil',5);
INSERT INTO table_livres VALUES(934,'','Pauvre Lampil','Pauvre Lampil',6);
INSERT INTO table_livres VALUES(935,'','Pauvre Lampil','Pauvre Lampil',7);
INSERT INTO table_livres VALUES(936,'','Guerre froide','421',1);
INSERT INTO table_livres VALUES(937,'','Bons baisers du 7eme ciel','421',2);
INSERT INTO table_livres VALUES(938,'','Scotch Malaria','421',5);
INSERT INTO table_livres VALUES(939,'','Falco','421',7);
INSERT INTO table_livres VALUES(940,'','Les annees de brouillard','421',8);
INSERT INTO table_livres VALUES(941,'','Morgane Angel','421',9);
INSERT INTO table_livres VALUES(942,'','Le seuil de Karlov','421',10);
INSERT INTO table_livres VALUES(942,'','L''exode','Les petits hommes',1);
INSERT INTO table_livres VALUES(943,'','Des petits hommes au brontoxique','Les petits hommes',2);
INSERT INTO table_livres VALUES(944,'','Les guerriers du passe','Les petits hommes',3);
INSERT INTO table_livres VALUES(945,'','Le lac de l'auto','Les petits hommes',4);
INSERT INTO table_livres VALUES(946,'','L''oeil du Cyclope','Les petits hommes',5);
INSERT INTO table_livres VALUES(947,'','Le vaisseau fantome','Les petits hommes',6);
INSERT INTO table_livres VALUES(948,'','Les ronces du samourai','Les petits hommes',7);
INSERT INTO table_livres VALUES(949,'','Du reve en poudre','Les petits hommes',8);
INSERT INTO table_livres VALUES(950,'','Le triangle du diable','Les petits hommes',9);
INSERT INTO table_livres VALUES(951,'','Le peuple des abysses','Les petits hommes',10);
INSERT INTO table_livres VALUES(952,'','Dans les griffes du seigneur','Les petits hommes',11);
INSERT INTO table_livres VALUES(953,'','Le guepier','Les petits hommes',12);
INSERT INTO table_livres VALUES(954,'','Les prisonniers du temps','Les petits hommes',13);
INSERT INTO table_livres VALUES(955,'','La planete Ranxerox','Les petits hommes',16);